Repository gokulrajanpillai/PyValidator, pull requests merged in 2022-10, with the labels that each got.

#14 5 create hello world python
  doc/test.txt
  src/.DS_Store
  src/hello_world.py
  tests/test.txt
Labels: enhancement, good first issue, hacktober

#16 Added Dockerfile from python base image
  Dockerfile
Labels: enhancement, hacktober

#17 Setted up basic sphinx doc
  doc/test.txt
  docs/source/index.rst
Labels: enhancement, good first issue, hacktober

#18 Added sample pyproject.toml
  pyproject.toml
Labels: enhancement, good first issue, hacktober

#19 Creating a basic README.md
  README.md
Labels: good first issue, hacktober

#21 Initial commit
  .github/workflows/on_push.yml
Labels: enhancement, hacktober
